# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.readExcelFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.readExcelFileButton.setObjectName("readExcelFileButton")
        self.gridLayout.addWidget(self.readExcelFileButton, 0, 2, 1, 1)
        self.errorTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.errorTextEdit.setObjectName("errorTextEdit")
        self.gridLayout.addWidget(self.errorTextEdit, 6, 1, 1, 1)
        self.workerListComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.workerListComboBox.setObjectName("workerListComboBox")
        self.gridLayout.addWidget(self.workerListComboBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.fileExtentionLabel = QtWidgets.QLabel(self.centralwidget)
        self.fileExtentionLabel.setObjectName("fileExtentionLabel")
        self.gridLayout.addWidget(self.fileExtentionLabel, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.personalDetailButton = QtWidgets.QPushButton(self.centralwidget)
        self.personalDetailButton.setObjectName("personalDetailButton")
        self.verticalLayout.addWidget(self.personalDetailButton)
        self.generalDetailButton = QtWidgets.QPushButton(self.centralwidget)
        self.generalDetailButton.setObjectName("generalDetailButton")
        self.verticalLayout.addWidget(self.generalDetailButton)
        self.gridLayout.addLayout(self.verticalLayout, 6, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.personalEditing = QtWidgets.QPushButton(self.centralwidget)
        self.personalEditing.setObjectName("personalEditing")
        self.gridLayout.addWidget(self.personalEditing, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "ANA EKRAN"))
        self.readExcelFileButton.setText(_translate("mainWindow", "DOSYA OKUNMA"))
        self.label.setText(_translate("mainWindow", "ÇALIŞANLAR:"))
        self.fileExtentionLabel.setText(_translate("mainWindow", "DOSYA SEÇİNİZ:"))
        self.personalDetailButton.setText(_translate("mainWindow", "PERSONAL DETAYLARI"))
        self.generalDetailButton.setText(_translate("mainWindow", "GENEL LİSTE"))
        self.personalEditing.setText(_translate("mainWindow", "PERSONAL İSLEMLERİ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
